name: APK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.8
  FLET_CLI_VERSION: 0.28.3  # Updated to 0.28.3
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1
  UV_NO_PROGRESS: 1
  FLUTTER_VERSION: 3.24.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Check Flutter Installation
      run: |
        flutter doctor -v

    - name: Install flet-cli ${{ env.FLET_CLI_VERSION }}
      run: |
        python -m pip install --upgrade pip
        pip install flet-cli==$FLET_CLI_VERSION

    - name: Verify pyproject.toml presence
      run: |
        if [ -f pyproject.toml ]; then
          echo "pyproject.toml found"
          cat pyproject.toml
        else
          echo "Error: pyproject.toml not found in repository root"
          exit 1
        fi

    - name: Flet Build APK
      run: |
        flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Inspect Generated AndroidManifest.xml
      run: |
        if [ -f obj/Debug/android/app/src/main/AndroidManifest.xml ]; then
          echo "AndroidManifest.xml contents:"
          cat obj/Debug/android/app/src/main/AndroidManifest.xml
        else
          echo "Warning: AndroidManifest.xml not found"
        fi

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build-artifact
        path: build/apk
        if-no-files-found: error
        overwrite: false
